### ISSUE TITLE
Support more diagram syntaxes

### ISSUE THREAD

**Issue by bra1nDump** [bra1nDump/show-me-chatgpt-plugin#3]
Kroki supports a variety of diagrams - GraphViz, Escalidraw, PlantUML etc. We currently only did prompt engineering to support mermaid graph TB diagrams.

**Comment by oscaramos** [comment]
Working on it!

**Comment by bra1nDump** [comment]
@oscaramos Let me know if you have any issues running it locally.

One thing I would caution about: adding more diagram types will lead to more potential syntax and thus rendering errors. 

To address this we have originally only moved to supporting mermaid and bias it to choose specifically graph diagrams. Searching GitHub showed graph TD, graph LR had many examples, so gpt had plenty of data to learn from.

2 concrete suggestions:
1. Let's start with one new syntax
2. Let's pick something that has many samples on GitHub

**Comment by VladimirAlexiev** [comment]
hi @bra1nDump ! 
I'd really love if you can add support for PlantUML. It has a lot more diagram types than Mermaid. I know a lot about it, and there's an active community (https://discord.gg/wsfjbxKYeK and other places) that can help.

Here are some stats on Github comparing Plantuml vs Mermaid:
- https://github.com/search?q=%60%60%60plantuml&type=repositories
![image](https://github.com/bra1nDump/show-me-chatgpt-plugin/assets/536250/95271bbd-21e1-46d6-9369-89ea7d0c0c7a)
- https://github.com/search?q=%60%60%60mermaid&type=repositories
![image](https://github.com/bra1nDump/show-me-chatgpt-plugin/assets/536250/2992952a-dd4e-4e84-a96e-ed08270bf5e9)

http://real-world-plantuml.com/ gathers many thousands of PlantUML diagrams from the wild.
It's at https://github.com/yfuruyama/real-world-plantuml.
Unfortunately it hasn't been updated since 2018 so it misses many of the newer diagram types: https://github.com/yfuruyama/real-world-plantuml/issues/4
